### ISSUE TITLE
deploy failed

### ISSUE THREAD

**Issue by geeorgey** [developerforce/salesforce-slack-starter-kit#22]
When I used this command to deploy, I got a copyfile error as shown below.
What is the cause of the error?

% node salesforce-slack-starter-kit/scripts/deploy.js

*** Please provide the following information: 
✔ Heroku App Name · lnest-salesforce-slack-starter
✔ Slack Bot Token · *********************************************************
✔ Slack Signing Secret · ********************************
✔ Salesforce Authorization Flow · jwt-bearer
✔ Existing SFDX DevHub Alias · myalias
✔ SFDX Scratch Org Alias · my-scratch-org

*** Starting the salesforce and heroku app setup ***
*** Creating Salesforce org ***

*** Setting up Salesforce App (step 1 of 3)
*** Creating scratch org
*** Fetching user data
*** ✔ Done with the Salesforce scratch org setup
*** Generating Certificates for Connected App
*** Creating Connected app
*** Creating Certificates for Salesforce Connected Apps ***
*** Deploying connected apps to Salesforce Environment (step 3 of 3)
*** ERROR: Error: ENOENT: no such file or directory, copyfile 'scripts/templates/slackApp.connectedApp-meta.xml' -> 'connectedApps/slackApp.connectedApp-meta.xml'

**Comment by geeorgey** [comment]
When I changed the execution directory, I got a different error.

$ cd salesforce-slack-starter-kit
$ node scripts/deploy.js

george@MacBook-Pro salesforce-slack-starter-kit % node scripts/deploy.js 
/Users/george/Desktop/dev/salesforce-slack-starter-kit/salesforce-slack-starter-kit

*** Please provide the following information: 
✔ Heroku App Name · lnest-salesforce-slack-starter
✔ Slack Bot Token · *********************************************************
✔ Slack Signing Secret · ********************************
✔ Salesforce Authorization Flow · jwt-bearer
✔ Existing SFDX DevHub Alias · slackforce
✔ SFDX Scratch Org Alias · slackforce-scratch-org

*** Starting the salesforce and heroku app setup ***
*** Creating Salesforce org ***

*** Setting up Salesforce App (step 1 of 3)
*** Creating scratch org
*** ERROR: Error: (node:49791) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by msrivastav13** [comment]
Are you on the latest code in the main branch? I suggest to use the main branch and make sure you have latest code.

**Comment by geeorgey** [comment]
Yes
Its latest code.

george@MacBook-Pro salesforce-slack-starter-kit % git pull                                  
Already up to date.

**Comment by msrivastav13** [comment]
I had this issue and I fixed it up using below PR

https://github.com/developerforce/salesforce-slack-starter-kit/pull/19

please double check that scratch org creation command uses the json argument as well

**Comment by geeorgey** [comment]
I deleted the working folder and tried to clone it again, but the same error occurred.

*** ERROR: Error: (node:50916) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by msrivastav13** [comment]
What version of sfdx cli you are on?

**Comment by msrivastav13** [comment]
Comment out the line https://github.com/developerforce/salesforce-slack-starter-kit/blob/b75f6e88a3fd086076fe8b82bac4c2ac165ade97/scripts/deploy/setupsalesforceorg.js#L22 in your script to bypass the error coming from sfdx cli

**Comment by geeorgey** [comment]
% sfdx --version
sfdx-cli/7.129.0 darwin-x64 node-v16.13.0

It works for me! > Comment out the line

Thank you @msrivastav13

**Comment by geeorgey** [comment]
There was a component error.
I seem to have been able to deploy the Heroku app.


*** Please provide the following information: 
✔ Heroku App Name · lnest-slackforce
✔ Slack Bot Token · *********************************************************
✔ Slack Signing Secret · ********************************
✔ Salesforce Authorization Flow · jwt-bearer
✔ Existing SFDX DevHub Alias · DevHub
✔ SFDX Scratch Org Alias · slackforce-scratch

*** Starting the salesforce and heroku app setup ***
*** Creating Salesforce org ***

*** Setting up Salesforce App (step 1 of 3)
*** Creating scratch org
*** Fetching user data
*** ✔ Done with the Salesforce scratch org setup
*** Generating Certificates for Connected App
*** Creating Connected app
*** Creating Certificates for Salesforce Connected Apps ***
*** Deploying connected apps to Salesforce Environment (step 3 of 3)
*** Deploying with SOAP API v53.0 ***
Deploy ID: 0Af0lxxxxxxxx
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/1 Components
SOURCE PROGRESS | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/1 Components


=== Component Failures [1]
Type   Name      Problem
─────  ────────  ─────────────────────────────────────────────
Error  slackApp  This profile is not found. Please enter a valid profile name and try again.

ERROR running force:source:deploy:  Deploy failed.
*** Create Heroku App with necessary configs

*** Setting up Heroku app (step 2 of 3)
*** Creating Heroku app lnest-slackforce
*** Adding Node.js Buildpack
*** Writing .env file for local development
*** Pushing app to Heroku
*** Setting remote configuration parameters
Setting APP_BASE and restarting lnest-slackforce... done, v4
APP_BASE: apps/slack-salesforce-starter-app
Setting SF_USERNAME and restarting lnest-slackforce... done, v5
SF_USERNAME: test-e5boqbxm4raj@example.com
Setting SF_LOGIN_URL and restarting lnest-slackforce... done, v6
SF_LOGIN_URL: https://test.salesforce.com
The authenticity of host 'heroku.com (50.19.85.132)' can't be established.
RSA key fingerprint is SHA256:8tF0wX2WquK45aGKs/Bh1dKmBXH08vxUe0VCJJWOA/o.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'heroku.com' (RSA) to the list of known hosts.
git@heroku.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
*** ✔ Done deploying Heroku app lnest-slackforce

**Comment by msrivastav13** [comment]
Looks like your profile name is not system administrator. Hence it is causing issues.

This could be because your Salesforce environment is in some other language than English.

In that case I suggest edit the template folder under scripts folder and make sure your connected app template has proper profile name based on your language.

I am keeping this issue open to fix at some point.

**Comment by geeorgey** [comment]
My environment was Japanese.
So I changed this one and it worked.
https://github.com/developerforce/salesforce-slack-starter-kit/blob/main/scripts/templates/slackApp.connectedApp-meta.xml#L9

- <profileName>System Administrator</profileName>
+ <profileName>システム管理者</profileName>

Thank you for your generous support.

**Comment by msrivastav13** [comment]
@geeorgey We moved to the permission set and also changed a lot of code. If you still facing the issue, please open a new issue! Thank you

**Comment by geeorgey** [comment]
Thanks! @msrivastav13
