### ISSUE TITLE
User auth doesn't work for users that aren't part of slack app admin permission set

### ISSUE THREAD

**Issue by ngiunta-salesforce** [developerforce/salesforce-slack-starter-kit#51]
Implementing the starter kit in my own project led me to have to create a 2nd connected app for user to user flow to work as they were not able to connect to the app created by the script that is limited to the Salesforce slack app admin permission set (as it should be).

**Comment by msrivastav13** [comment]
Where you not able to add other permission set to the connected app created by script?

We don't lock connected app created by script, so you should be able to add other permission to the same connected app.
